spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5430/user_test?ApplicationName=UserApp
    username: user-manager
    password: usermanager
    hikari:
      min-idle: 3
      maximum-pool-size: 6
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate:
        default_schema: user_schema
  jackson:
    serialization:
      write-dates-as-timestamps: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: task.manager.23.01@gmail.com
    password: wqqiqtpopwveuxep
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 80



jwt:
  secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw
  issuer: ITAcademy